"""questionnaire

Revision ID: 6387474e5ed4
Revises: 7389d3a50b57
Create Date: 2025-05-20 21:29:56.628241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6387474e5ed4'
down_revision: Union[str, None] = '7389d3a50b57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completed_questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('questionnaire_version', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_completed_questionnaires_user_id'), 'completed_questionnaires', ['user_id'], unique=False)
    op.create_table('questionnaire_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('queue', sa.TEXT(), nullable=False),
    sa.Column('answers', sa.TEXT(), nullable=False),
    sa.Column('answered_questions', sa.TEXT(), nullable=False),
    sa.Column('questionnaire_version', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questionnaire_states_user_id'), 'questionnaire_states', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questionnaire_states_user_id'), table_name='questionnaire_states')
    op.drop_table('questionnaire_states')
    op.drop_index(op.f('ix_completed_questionnaires_user_id'), table_name='completed_questionnaires')
    op.drop_table('completed_questionnaires')
    # ### end Alembic commands ###
