"""add view history table

Revision ID: 89e7ea94b9f5
Revises: 9cd6f5e0574f
Create Date: 2025-04-30 15:20:10.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '89e7ea94b9f5'
down_revision: Union[str, None] = '9cd6f5e0574f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('view_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.order_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_view_history_id'), 'view_history', ['id'], unique=False)
    op.create_index(op.f('ix_view_history_listing_id'), 'view_history', ['listing_id'], unique=False)
    op.create_index(op.f('ix_view_history_user_id'), 'view_history', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_view_history_user_id'), table_name='view_history')
    op.drop_index(op.f('ix_view_history_listing_id'), table_name='view_history')
    op.drop_index(op.f('ix_view_history_id'), table_name='view_history')
    op.drop_table('view_history')
    # ### end Alembic commands ### 