"""add user filters table

Revision ID: aee7ba56c8d3
Revises: 89e7ea94b9f5
Create Date: 2025-05-10 14:30:22.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'aee7ba56c8d3'
down_revision: Union[str, None] = '89e7ea94b9f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_filters',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True, default="rent"),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('price_min', sa.Integer(), nullable=False, default=500),
    sa.Column('price_max', sa.Integer(), nullable=False, default=15000),
    sa.Column('rooms_min', sa.Float(), nullable=False, default=1),
    sa.Column('rooms_max', sa.Float(), nullable=False, default=8),
    sa.Column('size_min', sa.Integer(), nullable=False, default=10),
    sa.Column('size_max', sa.Integer(), nullable=False, default=500),
    sa.Column('options', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_filters_user_id'), 'user_filters', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_filters_user_id'), table_name='user_filters')
    op.drop_table('user_filters')
    # ### end Alembic commands ### 