"""add_user_preference_vectors_table

Revision ID: b80ac323252f
Revises: fb5e4c7442ee
Create Date: 2025-08-06 13:33:49.151813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b80ac323252f'
down_revision: Union[str, None] = 'fb5e4c7442ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preference_vectors',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('cultural_level', sa.Float(), nullable=False),
    sa.Column('religiosity_level', sa.Float(), nullable=False),
    sa.Column('communality_level', sa.Float(), nullable=False),
    sa.Column('kindergardens_level', sa.Float(), nullable=False),
    sa.Column('maintenance_level', sa.Float(), nullable=False),
    sa.Column('mobility_level', sa.Float(), nullable=False),
    sa.Column('parks_level', sa.Float(), nullable=False),
    sa.Column('peaceful_level', sa.Float(), nullable=False),
    sa.Column('shopping_level', sa.Float(), nullable=False),
    sa.Column('safety_level', sa.Float(), nullable=False),
    sa.Column('preference_vector', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('questionnaire_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_constraint(op.f('favorites_user_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['firebase_uid'])
    op.drop_constraint(op.f('listings_neighborhood_id_fkey'), 'listings', type_='foreignkey')
    op.create_foreign_key(None, 'listings', 'neighborhoods', ['neighborhood_id'], ['yad2_hood_id'], ondelete='SET NULL')
    op.alter_column('neighborhood_features', 'hebrew_name',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('neighborhood_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_neighborhood_features_yad2_hood_id'), table_name='neighborhood_features')
    op.drop_column('neighborhood_features', 'id')
    op.alter_column('neighborhoods', 'city',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.create_unique_constraint(None, 'neighborhoods', ['hebrew_name'])
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.drop_constraint(op.f('view_history_user_id_fkey'), 'view_history', type_='foreignkey')
    op.create_foreign_key(None, 'view_history', 'users', ['user_id'], ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view_history', type_='foreignkey')
    op.create_foreign_key(op.f('view_history_user_id_fkey'), 'view_history', 'users', ['user_id'], ['firebase_uid'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_constraint(None, 'neighborhoods', type_='unique')
    op.alter_column('neighborhoods', 'city',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('neighborhood_features', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_neighborhood_features_yad2_hood_id'), 'neighborhood_features', ['yad2_hood_id'], unique=True)
    op.alter_column('neighborhood_features', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('neighborhood_features', 'hebrew_name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.create_foreign_key(op.f('listings_neighborhood_id_fkey'), 'listings', 'neighborhoods', ['neighborhood_id'], ['yad2_hood_id'])
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_user_id_fkey'), 'favorites', 'users', ['user_id'], ['firebase_uid'], ondelete='CASCADE')
    op.drop_table('user_preference_vectors')
    # ### end Alembic commands ###
