"""adding field to state

Revision ID: 107486f4bec5
Revises: 6f3b967c859e
Create Date: 2025-05-22 16:14:14.586883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '107486f4bec5'
down_revision: Union[str, None] = '6f3b967c859e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('completed_questionnaires_user_id_key', 'completed_questionnaires', type_='unique')
    op.drop_index('ix_completed_questionnaires_user_id_unique', table_name='completed_questionnaires')
    op.drop_column('completed_questionnaires', 'id')
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_questionnaire_states_user_id_unique', table_name='questionnaire_states')
    op.drop_constraint('questionnaire_states_user_id_key', 'questionnaire_states', type_='unique')
    op.drop_index('ix_questionnaire_states_user_id', table_name='questionnaire_states')
    op.create_index(op.f('ix_questionnaire_states_user_id'), 'questionnaire_states', ['user_id'], unique=False)
    op.drop_column('questionnaire_states', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questionnaire_states', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_index(op.f('ix_questionnaire_states_user_id'), table_name='questionnaire_states')
    op.create_index('ix_questionnaire_states_user_id', 'questionnaire_states', ['user_id'], unique=True)
    op.create_unique_constraint('questionnaire_states_user_id_key', 'questionnaire_states', ['user_id'])
    op.create_index('ix_questionnaire_states_user_id_unique', 'questionnaire_states', ['user_id'], unique=True)
    op.alter_column('favorites', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('completed_questionnaires', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_completed_questionnaires_user_id_unique', 'completed_questionnaires', ['user_id'], unique=True)
    op.create_unique_constraint('completed_questionnaires_user_id_key', 'completed_questionnaires', ['user_id'])
    # ### end Alembic commands ###
