"""pk change to pref

Revision ID: 5d5dc97670c3
Revises: 107486f4bec5
Create Date: 2025-05-22 16:17:51.065019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d5dc97670c3'
down_revision: Union[str, None] = '107486f4bec5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_preferences_id', table_name='user_preferences')
    op.drop_column('user_preferences', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index('ix_user_preferences_id', 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###
