"""add_user_foreign_keys

Revision ID: fb5e4c7442ee
Revises: 5d5dc97670c3
Create Date: 2025-05-22 16:24:24.658464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5e4c7442ee'
down_revision: Union[str, None] = '5d5dc97670c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'completed_questionnaires', 'users', ['user_id'], ['firebase_uid'])
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['firebase_uid'])
    op.create_foreign_key(None, 'questionnaire_states', 'users', ['user_id'], ['firebase_uid'])
    op.create_foreign_key(None, 'user_filters', 'users', ['user_id'], ['firebase_uid'])
    op.create_foreign_key(None, 'view_history', 'users', ['user_id'], ['firebase_uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'view_history', type_='foreignkey')
    op.drop_constraint(None, 'user_filters', type_='foreignkey')
    op.drop_constraint(None, 'questionnaire_states', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'completed_questionnaires', type_='foreignkey')
    # ### end Alembic commands ###
